### ISSUE TITLE
Procfile should in another folder

### ISSUE THREAD

**Issue by j-imy** [vasu-1/pygithub-bot#39]
required

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for opening the issue @j-imy! I will look into it ASAP!
 Till then show your love by staring my repos 😋.</td><td> <img alt='Coding' width='100px' height='100px' src='https://avatars.githubusercontent.com/u/89864614?v=4'></td></tr></tbody></table>

**Comment by vasu-1** [comment]
<br><table><tbody><tr><td>Thanks for closing this issue @j-imy! We hope you loved to work with our repository 😋.</td></tr></tbody></table>
